name: MarcelVermeulen
favicon: null
layout_spectrum: 1
typography_spectrum: 0.4127659
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Marcel Vermeulen
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#492c28'
    - '#060201'
    - '#f6d8bc'
    - '#d0a88e'
    - '#775b50'
  brandStrength: 1
  lightness: 0.8382978
  saturation: 0.5085106
  rhythmicContrast: 0.6297872
purpose: []
